### ISSUE TITLE
Failed datapack validation

### ISSUE THREAD

**Issue by Herobattler** [djsimmonds/tectonic-bop#2]
https://www.curseforge.com/minecraft/mc-mods/tectonic-bop/files/4486122

**Comment by djsimmonds** [comment]
please post modlist, log file, datapack order at worldgen

**Comment by Herobattler** [comment]
[mods.txt](https://github.com/djsimmonds/tectonic-bop/files/11224832/mods.txt)
[debug.log](https://github.com/djsimmonds/tectonic-bop/files/11224835/debug.log)
[latest.log](https://github.com/djsimmonds/tectonic-bop/files/11224836/latest.log)

**Comment by djsimmonds** [comment]
you didn't post a copy of your datapack ordering at world creation, but you can look at the other issue to see how it should look. however, i see a few problems already:
1) you are using a bunch of mods that use terrablender (wwoo, regions unexplored, river redux, quark), and presumably not disabling. these will break tectonic terrain gen and make using this mod pointless.
2) the error itself seems to focus on a particular bop biome; have you disabled origin valley in the biome toggles config in bop? if my mod tries to call a biome that you have disabled, it would likely lead to this crash.

**Comment by Herobattler** [comment]
Yes, a biome was disabled but there could have been a compat check or exeption on your mod's side to prevent a crash
